### ISSUE TITLE
NLP regex indonesia 

### ISSUE THREAD

**Issue by proesd** [axa-group/nlp.js#217]
## Summary

I want to parse some sentence with number in it
let say the utterance is "Nomor 1461"
but the response is Cannot read property 'shift' of undefined
I don't know why, if i write only the number it can show the correct answer

## Simplest Example to Reproduce

I'm adding this Training 
https://gitlab.com/ericksuryadinata/nlp-informatika-service/blob/master/app/Controllers/Http/Training/TrainingController.js

## Expected Behavior

it must return correct JSON like the others

## Your Environment

| Software             | Version |
|----------------------|---------|
| `nlp.js`   |    latest-master    |
| `node`               |     10.16    |
| `npm`                |     6.10.0    |
| Operating System     |    xubuntu 18.04  |

**Comment by jesus-seijas-sp** [comment]
Hello, fixed in version 3.2.1

**Comment by proesd** [comment]
Thanks,
but it still doesn't search the regex
manager.addRegexEntity('nbi', 'id', /^\d{9}$|^\d{10}$/gi)

the utterance is "jadwal kuliah hari kamis nbi 1461505276"
the entities only show 
```
{
        "start": 29,
        "end": 38,
        "len": 10,
        "accuracy": 0.95,
        "sourceText": "1461505276",
        "utteranceText": "1461505276",
        "entity": "number",
        "resolution": {
          "strValue": "1461505276",
          "value": 1461505276,
          "subtype": "integer"
        }
      },
      {
        "start": 29,
        "end": 38,
        "len": 10,
        "accuracy": 0.95,
        "sourceText": "1461505276",
        "utteranceText": "1461505276",
        "entity": "phonenumber",
        "resolution": {
          "value": "1461505276",
          "score": "0.5"
        }
      }
```
am I missing something ?

**Comment by proesd** [comment]
solved, the regex was wrong
i use this `/(?<=\s|^)\d{10}|(?<=\s|^)\d{9}/g`
