### ISSUE TITLE
NlpManager - can't disable logging

### ISSUE THREAD

**Issue by rmlamarche** [axa-group/nlp.js#351]
**Describe the bug**
I am unable to disable logging or change the logging function using NlpManager (or I am misinterpreting the docs)

**To Reproduce**
```javascript
const manager = new NlpManager({ languages: ['en'], nlu: { log: false } }); // <== from the docs

// add training data

(async() => {
  await manager.train();
  manager.save(path.join(__dirname, 'manager.nlp'));
})();
```

**Expected behavior**
Logging should be disabled.

**Screenshots**
```shell
# output in console
Epoch 1 loss 0.30498485110544915 time 0ms
Epoch 2 loss 0.15352931743830422 time 0ms
Epoch 3 loss 0.09343086821119338 time 0ms
Epoch 4 loss 0.06408766576962159 time 3ms
Epoch 5 loss 0.04535158248120372 time 1ms
Epoch 6 loss 0.032632077216463544 time 0ms
Epoch 7 loss 0.02379546841524644 time 0ms
Epoch 8 loss 0.017560640140445345 time 1ms
Epoch 9 loss 0.013098361078759236 time 0ms
Epoch 10 loss 0.009844168760897677 time 0ms
Epoch 11 loss 0.007450941518198192 time 0ms
Epoch 12 loss 0.0056750786942807545 time 1ms
Epoch 13 loss 0.004346232527698474 time 0ms
Epoch 14 loss 0.0033443165515810456 time 1ms
Epoch 15 loss 0.0025838075015013487 time 0ms
Epoch 16 loss 0.00200314439069048 time 0ms
Epoch 17 loss 0.0015575403950268403 time 0ms
Epoch 18 loss 0.001214089282809318 time 0ms
Epoch 19 loss 0.0009483871463641202 time 0ms
Epoch 20 loss 0.0007421808052774746 time 0ms
Epoch 21 loss 0.0005817158118388973 time 0ms
Epoch 22 loss 0.0004565591936588682 time 0ms
Epoch 23 loss 0.0003587499015443726 time 0ms
Epoch 24 loss 0.0002821842195680905 time 0ms
Epoch 25 loss 0.0002222769979482105 time 0ms
Epoch 26 loss 0.0001753104434394625 time 0ms
Epoch 27 loss 0.0001390853370533381 time 0ms
Epoch 28 loss 0.00010968138181185246 time 0ms
Epoch 29 loss 0.00008649965407775734 time 0ms
Epoch 30 loss 0.00006825340093393462 time 0ms
Epoch 31 loss 0.00005388511327178256 time 1ms
Epoch 32 loss 0.000042563754403676145 time 0ms
# ...
```

**Desktop (please complete the following information):**
Windows 10
Node 10.16.3
node-nlp latest (4.0.0-rc.15)

**Comment by akkitech** [comment]
I am also facing same issue.. any solution for this?

**Comment by jesus-seijas-sp** [comment]
Hello! Solved in version 4.0.0-rc.17

**Comment by rmlamarche** [comment]
Thanks so much @jesus-seijas-sp

**Comment by robertop87** [comment]
The issue is still reproducible in 4.3.0
A 2020-04-07T21:24:56.838522Z Epoch 74 loss 0.00020826116472905855 time 0ms 
A 2020-04-07T21:24:56.838550Z Epoch 75 loss 0.00019986363332316322 time 0ms 
A 2020-04-07T21:24:56.838626Z Epoch 76 loss 0.00019183343562181721 time 0ms 
A 2020-04-07T21:24:56.838642Z Epoch 77 loss 0.00018415310921868983 time 0ms 
A 2020-04-07T21:24:56.838712Z Epoch 78 loss 0.0001768055738574562 time 0ms 
A 2020-04-07T21:24:56.838753Z Epoch 79 loss 0.00016977459399820235 time 0ms 
A 2020-04-07T21:24:56.838807Z Epoch 80 loss 0.00016304582117373533 time 0ms 
A 2020-04-07T21:24:56.838868Z Epoch 81 loss 0.00015660452555626376 time 0ms 
A 2020-04-07T21:24:56.838914Z Epoch 82 loss 0.00015043718253671603 time 0ms 
A 2020-04-07T21:24:56.838976Z Epoch 83 loss 0.0001445313545045695 time 0ms 
A 2020-04-07T21:24:56.839036Z Epoch 84 loss 0.00013887444521496948 time 0ms 
A 2020-04-07T21:24:56.839071Z Epoch 85 loss 0.00013345544039584345 time 0ms 
A 2020-04-07T21:24:56.839124Z Epoch 86 loss 0.00012826279632534757 time 0ms 
A 2020-04-07T21:24:56.839169Z Epoch 87 loss 0.0001232868317493775 time 0ms 
A 2020-04-07T21:24:56.839212Z Epoch 88 loss 0.00011851733489682914 time 0ms 
A 2020-04-07T21:24:56.839300Z Epoch 89 loss 0.00011394507907327865 time 0ms 
A 2020-04-07T21:24:56.839331Z Epoch 90 loss 0.00010956111398082542 time 0ms 
A 2020-04-07T21:24:56.839364Z Epoch 91 loss 0.00010535718326516291 time 0ms 
A 2020-04-07T21:24:56.839424Z Epoch 92 loss 0.00010132527219642218 time 0ms 
A 2020-04-07T21:24:56.839450Z Epoch 93 loss 0.0000974578013953578 time 0ms 
A 2020-04-07T21:24:56.839510Z Epoch 94 loss 0.00009374721738123584 time 0ms 
A 2020-04-07T21:24:56.839551Z Epoch 95 loss 0.0000901868214944722 time 0ms 
A 2020-04-07T21:24:56.839619Z Epoch 96 loss 0.00008677019593742211 time 0ms 
A 2020-04-07T21:24:56.839640Z Epoch 97 loss 0.00008349088248124761 time 0ms 
A 2020-04-07T21:24:56.839686Z Epoch 98 loss 0.0000803431322917495 time 0ms 
A 2020-04-07T21:24:56.839736Z Epoch 99 loss 0.00007732110475816948 time 0ms 
A 2020-04-07T21:24:56.839778Z Epoch 100 loss 0.0000744193917095664 time 0ms
